version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/clients/go"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "go"]

  - package-ecosystem: "cargo"
    directory: "/clients/rust"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "rust"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "npm"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["dependencies", "ci"]
