[package]
name = "rubin-consensus"
version = "0.0.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }

[dependencies]
sha3 = "0.10"
num-bigint = "0.4"
num-traits = "0.2"
openssl-sys = "0.9"
